### ISSUE TITLE
Error in running manage.py makemigrations

### ISSUE THREAD

**Issue by ahm507** [edoburu/django-polymorphic-tree#33]
Hi,
I am using virtualenv with Python 2.7 and Django 1.8
I followed your readme directions, however, when I run:
$ manage.py makemigrations

I got an error an error, it seems a compatibility issue,  I concluded that because this error part [ from django.db.models.related import RelatedObject]

However, the complete trace is below. Wishing your support or directions how to resolve this issue.

Regards,
Ahmed

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/polymorphic/__init__.py", line 11, in <module>
    from .polymorphic_model import PolymorphicModel
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 22, in <module>
    from .base import PolymorphicModelBase
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/polymorphic/base.py", line 15, in <module>
    from .manager import PolymorphicManager
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/polymorphic/manager.py", line 9, in <module>
    from polymorphic.query import PolymorphicQuerySet
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/polymorphic/query.py", line 13, in <module>
    from .query_translate import translate_polymorphic_filter_definitions_in_kwargs, translate_polymorphic_filter_definitions_in_args
  File "/Users/Macpro/Projects/JudicialWF/env/lib/python2.7/site-packages/polymorphic/query_translate.py", line 10, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related

**Comment by vdboor** [comment]
Support for Django 1.8 has just been added, you can install v1.1 from PyPI!
